version: '{build}'
# build_cloud: zcd
# image: Linux

nuget:
  disable_publish_on_pr: true

configuration: Release

environment:
   # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NPM_TOKEN:
    secure: iNSaHS9YTyJXCAm4vZJaVu/BgIBMF9kfzUc8uxRAo28o3agRlLFSYyyzaNC1FYyzJ/kkCNX/QNwg1N/3yXeVSlJB/x19GLPZeJ6fsu9p1J8=
  GIT_AUTHOR_NAME:
    secure: B6rc3yafvlv33LqM4RWK3Q==
  GIT_COMMITTER_NAME:
    secure: B6rc3yafvlv33LqM4RWK3Q==
  GIT_AUTHOR_EMAIL:
    secure: CNIdeIKP5CY48G4+NqkRfNREo4HgGlkSSfzSCv6x0To=
  GIT_COMMITTER_EMAIL:
    secure: CNIdeIKP5CY48G4+NqkRfNREo4HgGlkSSfzSCv6x0To=
  nodejs_version: "12"

install:
- |
  curl -fSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
  chmod +x ./dotnet-install.sh
  sudo ./dotnet-install.sh --jsonfile global.json --no-path --install-dir /usr/share/dotnet

- |
  mkdir -p lib
  pushd lib
  curl -fSL --output deps.zip https://files.spoiledcat.com/deps.zip
  7z -y -bb3 x deps.zip
  popd

before_build:
- dotnet --list-sdks
- node --version
- npm --version
- ps: |
    $env:isPublic=0
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      $env:isPublic=1
    }

build_script:
- for i in 1 2 3 4 5; do dotnet restore -v Minimal && break || sleep 1; done
- ./build.sh -c $CONFIGURATION --ispublic $isPublic

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor

after_test:
- ps: |
    if ($env:GHPKEY) {
      $fileContent = "-----BEGIN OPENSSH PRIVATE KEY-----`n"
      $fileContent += $env:GHPKEY.Replace(' ', "`n")
      $fileContent += "`n-----END OPENSSH PRIVATE KEY-----`n"
      Set-Content \home\appveyor\.ssh\id_rsa $fileContent
    }

- ./publish.sh --branches --version $APPVEYOR_BUILD_VERSION --ispublic $isPublic
- ./pack.sh -c $CONFIGURATION --ispublic $isPublic
- ./publish.sh --npm --ispublic $isPublic

artifacts:
- path: build\**\*.nupkg
  name: NuGet
- path: build\**\*.tgz
  name: Npm

deploy:
  provider: NuGet
  api_key:
    secure: QyVIbwjTURMHVrR2W+cVp5rScQhALqq0dS/TuSgdrXee6uh8cV+KZCIpne1ARv+P
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
