version: '{build}'

nuget:
  disable_publish_on_pr: true

configuration: Release

environment:
   # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NPM_TOKEN:
    secure: iNSaHS9YTyJXCAm4vZJaVu/BgIBMF9kfzUc8uxRAo28o3agRlLFSYyyzaNC1FYyzJ/kkCNX/QNwg1N/3yXeVSlJB/x19GLPZeJ6fsu9p1J8=
  APPVEYOR_KEY:
    secure: cFZ3SHnfVQtRZedV/WL5qAL3SKjEmYpa/3g46r/1y20qiUieicctoY3SORHowqYHltFJ67P7rWc4t/dIMVj657oOA9n5rlgXRikuF2jOkOhuKACnsqW0RW9tA+VGrO86FGBHHrQePzLjgLn6jFwCX9B1Fop3txy27+rPJj3dVo3O7G7NJqXhvjM5kBtpw7jeM3n5H57PweOAR3tRNafz+U6DE2Te9NjSOSCy0DOA85Nnh4H+ffUrfd1xDsKzQMZPeYA6QJhw/AAZVEzaTzKDpuSrhJwqu8TqdIIjcLUCVuxVvtEwtbKdk191v8kW2icdNrDkEI8CxQHZmegf1MdAuUl2a51OmQpcLsF2ALAYuw0eM8hpAw+HEzo7ne15CTEu6Lyspo80fJoOj2AjvFpvV8lEUnMArNcIu2ufbUquHXvKAq3KjlcmFf8mHlnQARfiuzJftOIRZJhIfsJ2ikDeq28QCEUzzKEoc4ACl+cmNnjhrbk+WGDSIFZ4l9oQa/ds6ZEViw5ah5LKR16qtw2AChTB36mkC7Wtj/FEk6GHQCx6gDuu8mUCY5pCgQYMukjWk9nmE+0BHMBF1BOgPp71q+ROWKsWE096SP5ngatVBg+fl3QPH6aiBKweOjGtaSkqcI6XqhKWw/ctkKsk8bp8lxzPfw3a9PsqYyi4loyqFq/68HZ09AhIUXZFMi37pNezl0qtLNZOSMUx6/4uqts2ADIL3iZFRYpmP9EKVu1m7oSmVJZRUl0WKaggWYWWpZ7km0HtiwdNTt9tZg2dx9y4JfC8BcR9W9WckDiDIFQWliNoKyr1/j3aeQtyaZrGq3237xB4LpU1QJBzhIz88JdVZDF1X228ih4MDo1lnF1F8wDrqlg6Ux6b3cd4ummH9/4xI3ClP6A4IHiajgGYd0Q6x4Tda5HY+1is2AWJzX+F+UzHS0ICHaXN3f0Q0R70scjQuekvXjzaRrYPJYz5Oc4HPLSDY3o+ruGdCOJkBmIWnZvbnz8LNGKdsgj/SVITzbb7AhOIYn0ZZbdZb9sAzaTMY5t0JfXo3dfTchM6ZaevDG8GeI2lSGTH8eeNW6eseMM1x34f4rewcvZag6rTqkZuFoVtbnCjID0APHmeroZsWqQ9NlmQZSRMVHKJoRM/ndoBVO910MqwW+fyTXPOXpELgQ77yEy546hMxlK/oQkqae4yWFEn7scOZtSsYzb/ySkee6+x3QW2g2wjW7CJUoyVJQOHC4UUhwP9QQWeT9h/au+WboUbRc9/JzHlC2/+sMTtryxB0xY7ozalC2YXPbETP4zi/IHUAgKOFrvXQ5tChCXpNx6gCpS/JgbCtSOS4hsWiMp1Yg2nneBhzpil7g1AWvzph/5fs5OM5O23+h6WVth4RSK2/bgiEz1QAdBNXx0VHOH6wloeBGL7XUx+DZZUt3igLUa+bRgFM07Bn/x1B+plxnLiXZkgbgEkUPBqE4+KLCFRxRxHtQaBbQCIlEkcrOZrGhsv1MxzKa9ng6vJvAYHwa+iOqN+BjVvD14mXcBvX4YwtMBsTDFUUUWxdxpPKbym62VRzvUv8iGeW4j/rHxkSNJNkFV/Xl5ih2nP93p+IzR0dryAW5GR4whgZmkDIEnXfY9BAzsnU+Y+j1AfErLUHyFdPyFnWRj8JrX+0p+/O1SSPmb+JL/iQNJXdz856JXUIaz93L6o7W00KW2wmiwy9CTOSu8b+T8aKXH1fd6kEf+lbG8za9XiTLtnKVIXlL81gWv9izoa5qzkSa46oE+12OCY3/wZDFPoRdjRUoTlP5DoVNjB3oDr9B/J/BI1giiewF9dHvzdIMFECiFuWyFKeLxRnDt6jRr8ERsvTWee7jHIML8YKBcaw92oWe/bCilE8EP0kNeIid5TBHfafPDu93MvMTo2/wGGB6g077beWiVgVveKw4onfZ9ERI/li0YvZJwm6kSMw5ZskMDwON4HXSTHnk/uzI1Rb5pE8le2b7FV/BUHfDCLtYGqN8VBYgCiNByeImgFrAqzFpRC6uMkJ/vs/FP1h0ESl8sieBEEneVWGN58nC6JWpcuv2WZ12at+iDM+Jh14ogmj6F/XyGqreoZ41HjdPcDAeCFAlFIqDGA+TMXNkNQLjplUVOt9KBblXYmErPr8ihR/7qgcaRRTUGeIKok8Nt7mfnA1OLw/N7M4dVpn6oyHICQiuAjLy8TNgNkzkkNsSu5bt0J98RUjWNO2Y3QeZ0faVje045yDkVD89qKaLQJHSnLkfaNTXlw5cL7J0af/mseyk7Bi+UoLM2/ZCio3eA+ssuUcimAfIELoJo6hmOo4v1hVxh6LpJeiMygrGh3/u0Z56GB7isJ+10lbIgQZcWNf3qRWus/g8H35gdX9EIrqCO8QNBeSePoQdEKm+KTkZJSTFpQfwhsEyZp/ATSSxNVwV/Er8IOEkARG2SePjRTHKB7GVc7UCJh3IID3VTzoU+SJwYNOvCG7ACZ0qG+zJZJpXNEruyt4SmBJVSz2uV2wUlZ34y1Wb0kfjnt4d+4k+1TwVAZ3GNGy47AUi7S99pP0ENzjnLJ3c0q3NyOSVFO9jYtZ2BPbJ+KsRw5nhDM4GB4PJ3XokziG96Bghw3YYerksR49j32HYs08K1BpZ+if1rNjChVRfF8RhFOLDRqZTp0VryGYkEjpDpD0EP9iB9f7WkLvgsNyTIN2yBXfAqU+Yyb9uVlxORVLW4FP941beN+hdkyWfvxE9LhPqCZJLZ0uNQ355YwniaKPOh8hyhztFPvslg/NnAo75xAyJIzIu8N+4OP6bROoYYWNs8iTIDpIVBLkETIf3l1vu8xkua8agjpSD66WIOHvp23GNacLbgvPZwan9w3wgu8TcLt/0ZqLwDIyxCQFxEk9xg1xJqAJI3AEJ9YP+iXbTfX+aKXhJ4+t67blv3r3ifMgBQygOWTTrJPngEYPlWBp+mg/yomVO3ZPVT+Vvb7wYj6klQOmlW7JSuNhRGhWG9Li7BOyIVx7VxlK/7tH01oOoMmyjW0RET0hvPAUgyGSUqY2M8/wTKeFYYjtoYtcnUPIWSqXVN+GIPttGqKCY9pBtn8Njnxy8A0kUh5iEmkhUlNQCpUW/UgEd4ABp4eoJ8r+1s1XsQDm4wCYVztYDCe9NWoFQImXjilDqeaG9XhoBspb38uVIGhN8D/MCnF3k8Wsu7EECsC+sjADqd80WxEyFRmP+XyV5FBInMiYhwfbbK6cBoPLFmqvF0meDSPnTHCuJPByfjmcolaaJi5JSjRx4vM7ML1Da8Hc/0iWbjnGOZEr8gHMI3XeaADP4DpCCrx9ZGu8HXF2mZSL8Br5LwCnFcBjvzDE/iyhvN+RE8vYv6vqMWk7j/EZ6Ed3AKQr+SnittAV5vpbdU4DCYJjzwqxu2yzTbr4kyAMR7eLSeDZy327JuqaR0x0X+WSEub84NgOEnhcJY8cKINRojqbvixI3vSv1KjSJ8xb0fpvA5Lqr1TVaw+C2FowoBEBl8LUwjn+4mBYzR0eWvhYQJRActh0k91fzoEUc06cckkbsYOVJYM9TEdf01es1ziUo35R4bPuyH207hReNzM+UIZ6dYRmCM+mFoIM7n+yKqfDimqteWVXnwZQZxT6euqBy47iDv26y27BosCaPUHNhTlAI3fikJtel7y/1E5Lth7dMIwJgztPDNzy/rPPmFaSHS6OSetFhfdnLhtM+RkWAV/igpbh+mVkY0tM4rarUU7BZRk+nirokDYCPYbMAxhuBYs5kJAet+6jGUShdxtV+FdNnzWpwPctisYVKABqUwJBmeehijN669qOwt7BPDcWZD7Al/hTZqXz+X2p/PTMf6SeJj5/36244E555zjEiuce96R1KPMmim0M0qiaKyUa6pnLNp3LTCDsQxRvM8+SY6oYcTL8b/Z4HnnlLO5H2h4FPR46BsRE1BpHjk/uixhsDdGi6qCuAIygemrWjTGMLZmEo3RhwJxcBnls0VC5pzmtP3pDNhmam2U6VKwD/g5c4XY7XbDRTduU0Az3u6xKsaNsvxdRwOXw5iFiUFXnNi1cyjiah2u2DzTtr215/6AnI1vDcFv4Gvag5gQan8znwqtVXfhzHWF34KwltmaM9OgbKcCuGa9imZi1iOWwABRHmyEUtF63Q788VWr/cLSrLWFg9RGoGDycn6hBJCZTGlqeLtHaPhJyYtb19nxZldDnn5VTN71rFyHc6RAgBreQRi1RwfRWoa0G3vV15GuwLMTsOYsAgt+2qL30BxCQmdQwGB/RsItis2kWtMIYdBuDlYQLMauuUTsFK/UQaH7Bdv6Bnd/nHtJ3aSLXDxj23yGK4tnOpO65S1kTZsnMkE2QQcxvrU21cO1OzohfjIABnDt8JdGPxxuAf6tw5cD/3pszTlXa4Y1C7zqgzrc2cSNrGYfCLAYOgBmtY0WbS7eKLxVVqm85LbrGYTNIoaouStrb7zh+U+797sTftXPmQCMn7/IBDK7vumQCpi3VukdbOPvmsOkCszo0wbiMtDWBfRj19c=
  GIT_AUTHOR_NAME:
    secure: B6rc3yafvlv33LqM4RWK3Q==
  GIT_AUTHOR_EMAIL:
    secure: CNIdeIKP5CY48G4+NqkRfNREo4HgGlkSSfzSCv6x0To=

install:
- ps: scripts\Get-Deps.ps1

before_build:
# - dotnet --info
- ps: |
    if ($env:APPVEYOR_KEY) {
      Write-Output "CAN PUSH"
    }
    exit -1
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build --no-restore -c %CONFIGURATION%

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor

after_test:
- ps: |
    dotnet pack --no-build --no-restore -c $env:CONFIGURATION
    scripts\Pack-Packages.ps1
    $canPush = Test-Path $env:APPVEYOR_KEY
    if ($canPush) {
      $fileContent += $env:APPVEYOR_KEY.Replace(' ', "`n")
      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
      scripts\Publish-Branches.ps1
    }

artifacts:
- path: build\**\*.nupkg
  name: NuGet
- path: build\**\*.tgz
  name: Npm

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: hQSw9rzJnO5t0i20qqt/4pJ6fiXvXs9OV2iUdeLINuEfy2m8ZXLQyYDu7JkT7/E1
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true

after_deploy:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        npm config set //registry.spoiledcat.com/:_authToken $env:NPM_TOKEN
        npm config set always-auth true
        scripts\Publish-ToNpm.ps1
      }
