version: '{build}'

nuget:
  disable_publish_on_pr: true

configuration: Release

environment:
   # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NPM_TOKEN:
    secure: iNSaHS9YTyJXCAm4vZJaVu/BgIBMF9kfzUc8uxRAo28o3agRlLFSYyyzaNC1FYyzJ/kkCNX/QNwg1N/3yXeVSlJB/x19GLPZeJ6fsu9p1J8=
  APPVEYOR_KEY:
    secure: E48RhHF7PTrvHESGYevlE2ZLqgje4jY8B1Xs9zOtwPzkmKP8XpP8AaqtziP5Qs3HUk/Uf/IAIazCa4Oq32K492hilU44407+7QyrGikPEv5+0KjpXo8CsE/Mg521j+84SWnBzMSmwF6+60y74BB1XEW3TZfbUFJxP6ZnwTDkL1JrQyTSwqR2pLJcYsLAYEOg9dZ1CIN/+881Ylkl4GnUNaoC/VPnKM+0w30njfaZ+/u36bsDHjq/bB51KyZM0gu0DpGYIWZtTkfqoWWonwAf4EPMBHDDdkLCu/lX3P/O8K42gzM1Lg+Z8DTVMi0sZDBrr4Ym3Ly7b16tHzk8a4OcAs8YPmZ8zkX9ZRlzhCaVlxkTGARmuVmE2I02izZAL2aKdSLfnptFJajov3ZMPjrUkPCXAqlNnuTRisfGynuGtst9C9UwfXI5uv0pk2y+OaWWuxqiErS/eiYr7yjcbcpFZPXnPIdWYgPEfppIXwB0aBYJWycTve4znGOfoTa//ebjKbTffqPZmvonOi3JjzE9tNIIt2f3Lahuvix2av096bSRgyzgU2t/8mA7e1YLzjSlTvjVFDAGd/eC6vM2/0o1/WLS5vml83XbYgf/6QUU9+9ZAutqOXhAO+9pQN93nioh/GYNRJ6k3O3YrJ4W2iRggHHIb/6961IjvVjfV+wanOJVWwHFBVKhHpiDUt6dNxu249Hxa0Z9taZGgj0DzFbMwI3yvtXrKDDdXom4yBcwswpk+sPF3K/hqQbyo+dOUDd1PFYwJmH/cViDEn0ToeDs2XjIeTbkub0Nzua9iURHelEnhjSI7UE+m93xwzI1W8+cVGRY17Izj58cQ+tRwpeRpH49wPCPeD6dmnVpaaIxxslJ2QKekkJGpyWL3mmeSPEe/UhuJ6b767Sz2SbkOKY5j4qTkUe2mEcX9OcRqyyqnWAy3MWmx4tWteHUsKqBC3xx0pWWmD4DIYXNij2qjkeZRpjnAwjuFuxSC5Ok2jDdzreOglu+TacfiCxuKxY2ypYTmex7HRIhEdmYylm/L3Lh1aIFs3c1uTngi7/E2WGDK9JPtmZ0hCp+TbNzlGqJ/kzryapOSXFTe9WDlbQeqfFgd7x6JZStHtVLo7cGG7HC+9HimeH/srBoViqaP7+07g4ED4sqtzwnI+z7L/nWCBnwC50m8nwpOL6cRTSfBfC2cszlPNOTW979LKaE/C+BrHrpyNoc1jSLlCda0XkU6Nl+jQdCJ8posJvNc7ZSyJy7R7rlmmG21HCaQZUmqbtBYuNi5uOuguve0VuyCJ2Dt1qBIIvYAQWCwIlQqfNBD8u84axhwCf0OZo5rT9+l64lzc8fE04N4MrEJLfFq14iZVaNCS3gtNDVstxlKNn1wbvL5pIJu6MVQk7c8CZJOyKPVsf6fExF1B+HjLPmsyzdvuIy8uxsKNoOM5ZRl7nn7aDOC7sfIWw6CuVJbXU2R+Om1jri+F2QY2wSIy4912S/KGzDbktTm4sjNmfNyg/Ni8CFS8aZ39WMCJ9CGrvhlMiiJWubGXiMpE3kN+6oZLut21zSiSSZFdSBOP/Xkznqg5oS0Da/Oa4wRwEcoY0KMAWG5jigY4CDWbb8WfheJeelB5XpsliQtZ3Mh7YBk4SL7b88XylxDsaLwf3/5lAoYLVbWFu6qhFyacdLas492UcvcJiIXo9Y2v+CN+GJ/PJCZgE7rSnaJWTAsosSlpP7TI9yeHzBJ+pMqoGZhaWvODpCaoRuumpz3KltXOwVeSHDX3g1CZd/cr4LaW7Slfgrx24Ztz+JUu9ehL7DvL120V8N3kFeWdadG9hrN7FZcFnTDkvI2tc03I3ll9I3J9pJOYFS+3KDbvahY4s1JFEiyEZ+KjwM545rsdbdQa0R7LaxS1UKYIbu2vC27bEWqT39cY+gziVJzzfn5KFfun6hvV1C5svnF9bZTt179f/MpSGv4xx79WV3GifzRsbEy0cXlNGw+G8ZMkBQ6OOxBDMEtfOQPWJXpe0N8TZ9BKzYAhJg6a5bjfOtFr6p7B5Iy4KQRTVSBtydcCdQZpQbMm0MzcRTfq7XiSsbVEPeB29O91AzlSMqQfqvEHtCMcGV6ft254dSRKGOXwdwJMevu8Um/1PtV+YaNVdEBdvr9jCuV187eOCildpZ8SvRxxl67F8lxE1k7hruqmDoZn6eqRn2p0U+FEllNkucyQJ4m0ZH8Azo/cz+nHJIuMBYNmrEs8Z511aIsNI9D8JpoM5HijSB+RODxa5DRBNhg1pRjy5QQcTF7G6Lsl19ixOHsKf3tvhRwODtfM56zfLXwrkr3HVtbPOggz3BxYYJgAT/R17zD23s8a47N8VA6ETTEUyXfTFR8jDlFTyXP+jTBShEVqREvRTL+cf0hokT8LAZ2Z8Wg/1E01Ooe8+IsA4clZ7/qbibwOE83WFVQDbibUTr9BBlqTH9hYfGuE9hS/hUD9Gmt4OqIAsi2pHgLDf/RIag7e0n9UZKHGjDIoYIOa3iQdAe2cOCV435LTVGFVHsTwvkZP4/ptCZ6CuQTLGloAw67iQeb9Mi34Tk3Kk/2/Yqh/siDwuZLPH+hD5F0JPOr8qI1dcba86tLgRxRHeVWsOLvczJDAkDSN6JW5WrP+U1+EcRw7Sd3udpv/Sk+ejefaXv6CzhVS4jLoJH/P4WuQZf3fdCkUpl3Mn8a6QdmVjoMw0oTAkcjOgRf5Le8QdfOeDZYhDeAMcY+lcUokLhGJKdinFGF7X8KKPVDyxcNyfo865Q0TXQs8DFqv8z/ME5NvbbY8oZGH1fAgzj9ADHLkW2ShL9ZvSsk0BrGTemU8WwMjB3mBomKwG56cG8+vEr4xdLpY0MrivJd2UgmrSszhLwErZh4XulSvrTXbkCE+UVJimwDvN8m3+M0xxyWCGflv6WH8eKwGl9w58uAdKMFu9AcrYWuIJe+0NwdRqZE9lAlCQTNiDBTIOpMmQWcQYjTEAjVVtk458Orrfi+EV72kjjzrDlRaotvYVL3zCsE/gGQirKDQobrItbqojF/jfwUvv2SAp7UANtOHPSyi/Lc8O2Yv/onvhdpOGxdkwdQokHtHo4O3ITW08iGZbyGt4hoxQbiRhJ/L+/eMasHOgyaVyRY5r5gpT3b7VYSVOxxfpuGoeQZbC6n/mMBEsFS1kFdopi6/TLssMaYG73cnKFlC+sxG3QiK7G/pO0uLHVynBsBTSHQ4fHe5OYHZ4Q8tg4P9Kp7j9dbuFSCgLWRzFDp3f+6r7Bs7xoztGo8+1d1Vyez2VuGeC0Kpnr5ecTngomXixBVzyhFk9VwBVdse4L1bqYpW6yudXHN7Ydt9ZBHx4f/80py4A1whGq5dREq0rnMEAS8QBTY1lSshAZRdOJ9o0FNgScLlvkEm3TUyBb08hVr8c1jY2CEdi7m+Vcw1HBYbuujMheltdad3hJjfQ7156mrb70T/BnJTHIBWkfp/VyssLn9WqIhV+vDtO039Zuk0WUmVVle1cs3HqcUDKGRH+Id2ILk+p+C/oXYY9IF9P/COsD3C/J2j9EH2dqimXCc8Wuka1NVhrDzcls7dLlPdTfmpGwS8hv5beZUV5JVjX8+NXzMFiYFDP6ZC9mdpM74rCI1KQ/FgpyuEEchOT5+sxql6E2TYDpD/JiA7HM4UblIHdb5xoj7EEz/v/xp40MXzU94QvSnK58C1eF+GxIpb6QEi4uLsg5SJoeW7F4o7W4oOgnYDiwzvVd2tvCx7z2hhVeriRP9qrSru7LCf55gbI5YZ5oLw6t5hEbQTYqmIHhUXXis2blhUywsAy12P7H3LfudKwdp9WFVANpXLFgmbBWpTZJJKVBcqGebuGoeyXP32D8fhLGckpTdIcDzBBOZlY8SpH8pVEvsIVdt0O3FPBhuLwne8FEApCa0MuAjNZSp8UVyJ9/lFqTdz+lxQT4EUDd1qBDhCYVkhKUx2btqEjWSt51lsRdgGBEXGvO9agESQfLXSECo8oACVONQWTgjq+GbEYMn2nwgLY2TQP7VPTGdYR0NvpW17fFt05ZlkqxZhvlrpSUkaM7y9g4j9tLCB2GXexzh7FcMF6/LBznqPKSN7B86yH3j3YheCXKRxRRhtYLcRJ4yduLyutyG2LxHPGmpRA4vfQdI4Acv9Z/IXdGORZu1PT74AQRsx+BbWRruGRMzzxPLnLsmDGOvd588ith6NqY/OOc4mOc7r768Z82jRJ0RbE3ZzcnA+0szC8vLnPAv4mIBybNVq1GqYBhgSswBqBVonGG96Ed5VZGHIEUOHInoVvQ22nU37yzphj7SkINFibK2FJHpezNOGrWrwpIHxAGSwhIxwfnYNduVjnGWQraPsPZ4AemdF6UH+cP9NsHRD/4mOJUGR8vcU/39feNgTTOS5/tKXICV0HF3bSN7tUysQStHS4J
  GIT_AUTHOR_NAME:
    secure: B6rc3yafvlv33LqM4RWK3Q==
  GIT_COMMITTER_NAME:
    secure: B6rc3yafvlv33LqM4RWK3Q==
  GIT_AUTHOR_EMAIL:
    secure: CNIdeIKP5CY48G4+NqkRfNREo4HgGlkSSfzSCv6x0To=
  GIT_COMMITTER_EMAIL:
    secure: CNIdeIKP5CY48G4+NqkRfNREo4HgGlkSSfzSCv6x0To=

install:
- ps: scripts\Get-Deps.ps1

before_build:
# - dotnet --info
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build --no-restore -c %CONFIGURATION%

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor

after_test:
- ps: |
    dotnet pack --no-build --no-restore -c $env:CONFIGURATION
    scripts\Pack-Packages.ps1
    if ($env:APPVEYOR_KEY) {
      $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
      $fileContent += $env:APPVEYOR_KEY.Replace(' ', "`n")
      $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
      scripts\Publish-Branches.ps1
    }

artifacts:
- path: build\**\*.nupkg
  name: NuGet
- path: build\**\*.tgz
  name: Npm

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: hQSw9rzJnO5t0i20qqt/4pJ6fiXvXs9OV2iUdeLINuEfy2m8ZXLQyYDu7JkT7/E1
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true

after_deploy:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        npm config set //registry.spoiledcat.com/:_authToken $env:NPM_TOKEN
        npm config set always-auth true
        scripts\Publish-ToNpm.ps1
      }
