name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish packages'
        type: boolean
        required: false
        default: false
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v4
    - uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: dependencies
      run: |
        mkdir -p lib
        pushd lib
        curl -fSL --output deps.zip https://files.spoiledcat.com/deps.zip
        7z -y -bb3 x deps.zip
        popd
    - run: dotnet --list-sdks
    - run: node --version
    - run: npm --version

    - run: echo "isPublic=0" >> $GITHUB_ENV
    - if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      run: echo "isPublic=1" >> $GITHUB_ENV

    - if: ${{ github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/') }}
      run: echo "isPublic=1" >> $GITHUB_ENV

    - run: for i in 1 2 3 4 5; do dotnet restore -v Minimal && break || sleep 1; done
    - run: ./build.sh -c $CONFIGURATION --ispublic $isPublic --trace
    - run: ./test.sh -c $CONFIGURATION --ispublic $isPublic

    - name: SpoiledBot
      id: token
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ secrets.SPOILEDBOT_ID }}
        private_key: ${{ secrets.SPOILEDBOT_KEY }}

    # this lets us do commits and pushes without fiddling with keys
    - name: GH cli
      run: |
        gh --version
        echo "${{ steps.token.outputs.token }}" | gh auth login --with-token
        gh auth status
        git config --global user.name "SpoiledBot"
        git config --global user.email "github@spoiledcat.net"

    - run: ./publish.sh --branches --version ${NBGV_NpmPackageVersion} --ispublic $isPublic
      if: ${{ github.event_name != 'workflow_dispatch' || inputs.publish }}

    - run: ./pack.sh -c $CONFIGURATION --ispublic $isPublic

    - run: ./publish.sh --npm --ispublic $isPublic
      if: ${{ github.event_name != 'workflow_dispatch' || inputs.publish }}

    - uses: actions/upload-artifact@v4
      with:
        path: 'build/**/*.nupkg'

    - uses: actions/upload-artifact@v4
      with:
        path: 'build/**/*.tgz'
